# Generated by Django 5.0.3 on 2024-03-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('globalname', models.CharField(max_length=100)),
            ],
        ),
    ]
