# Generated by Django 5.0.3 on 2024-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
